### ISSUE TITLE
Header-Issue

### ISSUE THREAD

**Issue by rgl1234** [florian-h05/webrtc-sip-gw#6]
Hello @florian-h05 
Do you have an ides how I can solve the issue "required headers not present" ? I try to user your gw for registring at a starface-pbx......Can you help?
Thanks a lot
René

webrtc-sip-gw    |  1(19) INFO: <script>: Setting new Contact header: <sip:STARFACE@192.168.105.10:5060;alias=192.168.105.10~5060~1>
webrtc-sip-gw    |  9(27) INFO: <script>: HTTP Request Received
webrtc-sip-gw    |  9(27) WARNING: websocket [ws_handshake.c:271]: ws_handle_handshake(): required headers not present

**Comment by florian-h05** [comment]
These log messages are normal because the container‘s health check is pinging Kamailio. I should probably improve or disable the health check to get rid of those messages …

**Comment by rgl1234** [comment]
thanks a lot @florian-h05 for your feedback....so this should be ok....
But currently I face still an issue trying to register with a starface-pbx.... mabye you have an idea how to solve the following error....I think it could be related to nat....do you have an idea?

![image](https://github.com/florian-h05/webrtc-sip-gw/assets/11720329/acbd960c-3c7a-425b-98d4-7b7bd0b4e323)

**Comment by florian-h05** [comment]
That really seems to be a problem, but unfortunately I have no idea, sorry.

**Comment by rgl1234** [comment]
thank @florian-h05 
no problem....I will need to investigate further....hope to find a solution...

**Comment by Bonze255** [comment]
I use the gateway mit my fritzbox ans Jssip client. The Dcoker logs show me 

> 
 9(27) INFO: <script>: HTTP Request Received
 9(27) WARNING: websocket [ws_handshake.c:271]: ws_handle_handshake(): required                                   headers not present
 9(27) INFO: <script>: HTTP Request Received
 9(27) WARNING: websocket [ws_handshake.c:271]: ws_handle_handshake(): required                                   headers not present
 9(27) INFO: <script>: HTTP Request Received
 9(27) WARNING: websocket [ws_handshake.c:271]: ws_handle_handshake(): required                                   headers not present
 9(27) INFO: <script>: HTTP Request Received
 9(27) WARNING: websocket [ws_handshake.c:271]: ws_handle_handshake(): required                                   headers not present
 9(27) INFO: <script>: HTTP Request Received
 9(27) WARNING: websocket [ws_handshake.c:271]: ws_handle_handshake(): required                                   headers not present
 9(27) INFO: <script>: HTTP Request Received
 9(27) WARNING: websocket [ws_handshake.c:271]: ws_handle_handshake(): required     

I don't know what I'm doing wrong, but the sip client works, but I still get this error message.

**Comment by florian-h05** [comment]
Have you read the thread above?

> These log messages are normal because the container‘s health check is pinging Kamailio. I should probably improve or disable the health check to get rid of those messages …

**Comment by Bonze255** [comment]
sorry, i did not read it correctly

**Comment by florian-h05** [comment]
I have created an issue for improving the health check (#7), therefore I will close this issue.
