### ISSUE TITLE
Question does it work correctly? 

### ISSUE THREAD

**Issue by Bonze255** [florian-h05/webrtc-sip-gw#8]
i try to use this docker container with a fritzbox and jssip softphone..
the docker container is on a diffrent pc and without a ssl-cert.
i test the script without encryption, the normal ws:// ... But I have the problem that I can call other phones with my Jssip-Phone and everything works fine. But when I call the Jssip-Phone from another device, it rings, but the moment I pick up, the whole thing throws me an error. Do you have any idea what could be the reason for this ? 
Is it maybe because of the missing certificate? I read that this would be necessary? Do you have an working javascript softphone code, as an example for me? 

>**REGISTER sip:fritz.box SIP/2.0**
Via: SIP/2.0/WS 22med1ou7ji1.invalid;branch=z9hG4bK4090291
Max-Forwards: 69
To: <sip:smartvisupanel2@fritz.box>
From: "VISU" <sip:smartvisupanel2@fritz.box>;tag=uhstlr3r01
Call-ID: b7s2rh2kb3rjmkv84njdu4
CSeq: 3 REGISTER
Authorization: Digest algorithm=MD5, username="smartvisupanel2", realm="fritz.box", nonce="15738E3F9DFE4A4B", uri="sip:fritz.box", response="95f2c87b1e5ef94956abce6452d6f4b5"
Contact: <sip:8uslkn9u@22med1ou7ji1.invalid;transport=ws>;+sip.ice;reg-id=1;+sip.instance="<urn:uuid:59613d40-1aab-4f65-80d5-eff865a3d7de>";expires=600
Expires: 600
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS,REFER,INFO,NOTIFY
Supported: path,gruu,outbound
User-Agent: JsSIP 3.10.0
Content-Length: 0

> **SIP/2.0 200 OK**
> Via: SIP/2.0/WS 22med1ou7ji1.invalid;rport=57665;received=192.168.178.27;branch=z9hG4bK4090291
> From: "VISU" <sip:smartvisupanel2@fritz.box>;tag=uhstlr3r01
> To: <sip:smartvisupanel2@fritz.box>;tag=29F62F8CA505B636
> Call-ID: b7s2rh2kb3rjmkv84njdu4
> CSeq: 3 REGISTER
> Contact: <sip:smartvisupanel2@192.168.178.57:5060>;expires=300
> User-Agent: AVM FRITZ!Box 7430 146.07.31 (Sep  2 2023)
> Supported: 100rel,replaces,timer
> Allow-Event: telephone-event,refer,reg
> Allow: INVITE,ACK,OPTIONS,CANCEL,BYE,UPDATE,PRACK,INFO,SUBSCRIBE,NOTIFY,REFER,MESSAGE,PUBLISH
> Accept: application/sdp, multipart/mixed
> Accept-Encoding: identity
> Content-Length: 0
> 
> **INVITE sip:8uslkn9u@22med1ou7ji1.invalid;transport=ws SIP/2.0**
> Record-Route: <sip:192.168.178.57:8090;transport=ws;r2=on;lr=on;rtp=bridge;rtp=ws>
> Record-Route: <sip:192.168.178.57;r2=on;lr=on;rtp=bridge;rtp=ws>
> Via: SIP/2.0/WS  192.168.178.57:8090;branch=z9hG4bK74ac.876ea268bd98b50c2832ef50bc754269.0
> Via: SIP/2.0/UDP 192.168.178.1:5060;rport=5060;branch=z9hG4bK70B5F82BA0823D4D
> From: "Mobilteil 1" <sip:**610@fritz.box>;tag=7D692FA76198203C
> To: <sip:smartvisupanel2@192.168.178.57:5060>
> Call-ID: 020D6725F768D512@192.168.178.1
> CSeq: 55 INVITE
> Contact: <sip:1D845E6ED095C33CA2A1984C17A12@192.168.178.1;alias=192.168.178.1~5060~1>
> Max-Forwards: 69
> P-Called-Party-ID: <sip:**9@fritz.box>
> Expires: 120
> Session-Expires: 600;refresher=uac
> Min-SE: 90
> User-Agent: AVM FRITZ!Box 7430 146.07.31 (Sep  2 2023)
> Supported: 100rel,replaces,timer
> Allow-Events: telephone-event,refer
> Allow: INVITE,ACK,OPTIONS,CANCEL,BYE,UPDATE,PRACK,INFO,SUBSCRIBE,NOTIFY,REFER,MESSAGE,PUBLISH
> Content-Type: application/sdp
> Accept: application/sdp, multipart/mixed
> Accept-Encoding: identity
> Content-Length:   864
> P-hint: outbound
> v=0
> o=user 12342376 12342376 IN IP4 192.168.178.57
> s=call
> c=IN IP4 192.168.178.57
> t=0 0
> m=audio 23454 RTP/SAVPF 9 8 0 2 102 100 99 101 97 120 121
> a=mid:1
> a=rtpmap:9 G722/8000
> a=rtpmap:8 PCMA/8000
> a=rtpmap:0 PCMU/8000
> a=rtpmap:2 G726-32/8000
> a=rtpmap:102 G726-32/8000
> a=rtpmap:100 G726-40/8000
> a=rtpmap:99 G726-24/8000
> a=rtpmap:101 telephone-event/8000
> a=fmtp:101 0-15
> a=rtpmap:97 iLBC/8000
> a=fmtp:97 mode=30
> a=rtpmap:120 PCMA/16000
> a=rtpmap:121 PCMU/16000
> a=sendrecv
> a=rtcp:23455
> a=rtcp-mux
> a=setup:actpass
> a=fingerprint:sha-256 FD:3B:9D:7E:85:1B:1C:9C:2F:DC:1D:53:2D:5E:26:23:12:19:0A:EC:8F:BE:8B:68:B1:DB:CD:10:26:78:49:3D
> a=ice-ufrag:eNAfBzci
> a=ice-pwd:cj1LbH46AkKhdhcffMP1Ghwi9J
> a=candidate:7OpuYiObkcXO7RiN 1 UDP 2130706431 192.168.178.57 23454 typ host
> a=candidate:7OpuYiObkcXO7RiN 2 UDP 2130706430 192.168.178.57 23455 typ host
> 
> 
> **SIP/2.0 100 Trying**
> Via: SIP/2.0/WS  192.168.178.57:8090;branch=z9hG4bK74ac.876ea268bd98b50c2832ef50bc754269.0
> Via: SIP/2.0/UDP 192.168.178.1:5060;rport=5060;branch=z9hG4bK70B5F82BA0823D4D
> To: <sip:smartvisupanel2@192.168.178.57:5060>
> From: "Mobilteil 1" <sip:**610@fritz.box>;tag=7D692FA76198203C
> Call-ID: 020D6725F768D512@192.168.178.1
> CSeq: 55 INVITE
> Supported: timer,ice,replaces,outbound
> Content-Length: 0
> 
> **SIP/2.0 180 Ringing**
> Record-Route: <sip:192.168.178.57:8090;transport=ws;r2=on;lr=on;rtp=bridge;rtp=ws>
> Record-Route: <sip:192.168.178.57;r2=on;lr=on;rtp=bridge;rtp=ws>
> Via: SIP/2.0/WS  192.168.178.57:8090;branch=z9hG4bK74ac.876ea268bd98b50c2832ef50bc754269.0
> Via: SIP/2.0/UDP 192.168.178.1:5060;rport=5060;branch=z9hG4bK70B5F82BA0823D4D
> To: <sip:smartvisupanel2@192.168.178.57:5060>;tag=qfqfjnnui0
> From: "Mobilteil 1" <sip:**610@fritz.box>;tag=7D692FA76198203C
> Call-ID: 020D6725F768D512@192.168.178.1
> CSeq: 55 INVITE
> Contact: <sip:8uslkn9u@22med1ou7ji1.invalid;transport=ws>
> Supported: timer,ice,replaces,outbound
> Content-Length: 0
> 
> **INVITE sip:smartvisupanel2@192.168.178.57:5060 SIP/2.0**
> Record-Route: <sip:192.168.178.57:8090;transport=ws;r2=on;lr=on;nat=yes;rtp=bridge>
> Record-Route: <sip:192.168.178.57;r2=on;lr=on;nat=yes;rtp=bridge>
> Via: SIP/2.0/WS  192.168.178.57:8090;branch=z9hG4bK74ac.876ea268bd98b50c2832ef50bc754269.1
> Via: SIP/2.0/UDP 192.168.178.1:5060;rport=5060;branch=z9hG4bK70B5F82BA0823D4D
> From: "Mobilteil 1" <sip:**610@fritz.box>;tag=7D692FA76198203C
> To: <sip:smartvisupanel2@192.168.178.57:5060>
> Call-ID: 020D6725F768D512@192.168.178.1
> CSeq: 55 INVITE
> Contact: <sip:1D845E6ED095C33CA2A1984C17A12@192.168.178.1;alias=192.168.178.1~5060~1>
> Max-Forwards: 69
> P-Called-Party-ID: <sip:**9@fritz.box>
> Expires: 120
> Session-Expires: 600;refresher=uac
> Min-SE: 90
> User-Agent: AVM FRITZ!Box 7430 146.07.31 (Sep  2 2023)
> Supported: 100rel,replaces,timer
> Allow-Events: telephone-event,refer
> Allow: INVITE,ACK,OPTIONS,CANCEL,BYE,UPDATE,PRACK,INFO,SUBSCRIBE,NOTIFY,REFER,MESSAGE,PUBLISH
> Content-Type: application/sdp
> Accept: application/sdp, multipart/mixed
> Accept-Encoding: identity
> Content-Length:   491
> P-hint: outbound
> v=0
> o=user 12342376 12342376 IN IP4 192.168.178.57
> s=call
> c=IN IP4 192.168.178.57
> t=0 0
> m=audio 23476 RTP/AVP 9 8 0 2 102 100 99 101 97 120 121
> a=rtpmap:9 G722/8000
> a=rtpmap:8 PCMA/8000
> a=rtpmap:0 PCMU/8000
> a=rtpmap:2 G726-32/8000
> a=rtpmap:102 G726-32/8000
> a=rtpmap:100 G726-40/8000
> a=rtpmap:99 G726-24/8000
> a=rtpmap:101 telephone-event/8000
> a=fmtp:101 0-15
> a=rtpmap:97 iLBC/8000
> a=fmtp:97 mode=30
> a=rtpmap:120 PCMA/16000
> a=rtpmap:121 PCMU/16000
> a=sendrecv
> a=rtcp:23477
> 
> **SIP/2.0 482 Loop Detected**
> Via: SIP/2.0/WS  192.168.178.57:8090;branch=z9hG4bK74ac.876ea268bd98b50c2832ef50bc754269.1
> Via: SIP/2.0/UDP 192.168.178.1:5060;rport=5060;branch=z9hG4bK70B5F82BA0823D4D
> To: <sip:smartvisupanel2@192.168.178.57:5060>;tag=cekqukbrbm
> From: "Mobilteil 1" <sip:**610@fritz.box>;tag=7D692FA76198203C
> Call-ID: 020D6725F768D512@192.168.178.1
> CSeq: 55 INVITE
> 
> 
> **ACK sip:smartvisupanel2@192.168.178.57:5060 SIP/2.0**
> Via: SIP/2.0/WS  192.168.178.57:8090;branch=z9hG4bK74ac.876ea268bd98b50c2832ef50bc754269.1
> From: "Mobilteil 1" <sip:**610@fritz.box>;tag=7D692FA76198203C
> To: <sip:smartvisupanel2@192.168.178.57:5060>;tag=cekqukbrbm
> Call-ID: 020D6725F768D512@192.168.178.1
> CSeq: 55 ACK
> Max-Forwards: 69
> Content-Length: 0
> 
> 
> **SIP/2.0 488 Not Acceptable Here**
> Via: SIP/2.0/WS  192.168.178.57:8090;branch=z9hG4bK1368.414027032cc6771048fda7b823d6e3e5.0
> Via: SIP/2.0/UDP 192.168.178.1:5060;rport=5060;branch=z9hG4bKA800366E8E9B37F8
> To: <sip:smartvisupanel2@192.168.178.57:5060>;tag=7vblfd2r18
> From: "Mobilteil 1" <sip:**610@fritz.box>;tag=D33AF1BB22DB324D
> Call-ID: BA7669EC7F04F929@192.168.178.1
> CSeq: 56 INVITE
> Supported: timer,ice,replaces,outbound
> Content-Length: 0
> 
> ### JsSIP:WARN:RTCSession emit "peerconnection:setremotedescriptionfailed" [error:DOMException: Illegal audio/video payload type "2" at level 0
> 
> JsSIP:Transport received text message:
> ACK sip:9c67bqtc@onqmfbuu75fj.invalid;transport=ws SIP/2.0
> Via: SIP/2.0/WS  192.168.178.57:8090;branch=z9hG4bK1368.414027032cc6771048fda7b823d6e3e5.0
> From: "Mobilteil 1" <sip:**610@fritz.box>;tag=D33AF1BB22DB324D
> To: <sip:smartvisupanel2@192.168.178.57:5060>;tag=7vblfd2r18
> Call-ID: BA7669EC7F04F929@192.168.178.1
> CSeq: 56 ACK
> Max-Forwards: 69
> Content-Length: 0

**Comment by florian-h05** [comment]
> Do you have any idea what could be the reason for this ?

Unfortunately, no.

> Is it maybe because of the missing certificate?

As outgoing calls work, I don't think so.

>  Do you have an working javascript softphone code, as an example for me?

Yes, I have actually integrated JsSIP into the openHAB Main UI and there it is running very fine with this Docker container and my Fritz!Box. 

For the code, see https://github.com/openhab/openhab-webui/blob/07aacc9ee52a5f726c4a5feb46606edb6932ba0c/bundles/org.openhab.ui/web/src/components/widgets/system/oh-sipclient.vue.
I don't know how experienced you are with VueJS, however that does not matter. The important code is inside the `<script>` tags.

**Comment by Bonze255** [comment]
the docker log ,  shows me this, .. 

> Current Contact header: <sip:8i886kt4@7a4metfal6od**.invalid**;transport=w                                                           s>;+sip.ice;reg-id=1;+sip.instance="<urn:uuid:96845fcf-1474-48c3-a0ab-5d8c31bfb764>";expires=                                                           600

google says, that is maybe a  a problem for imcoming calls, but why?

**Comment by florian-h05** [comment]
I have set the `TLS_DISABLE` environment variable to `true` to disable the internal TLS.
I am using Nginx, not Apache, as reverse-proxy: Proxy the ws port 8090, but set the headers for WebSocket connection:

```
    location /sip {
        proxy_pass                    http://127.0.0.1:8090; # Adjust to your webrtc-sip-gw Docker host's IP
        proxy_http_version            1.1;
        proxy_set_header Upgrade      $http_upgrade;
        proxy_set_header Connection   "upgrade";
        proxy_read_timeout            86400;
    }
```

This way I can use the same certificate for everything on this machine, just makes life way easier to have one cert less to manage. Before I used nginx, I used one certificate on my openHAB host, and a different certficate for webrtc-sip-gw on an extra host, and it worked fine.

I guess you have some misconfiguration in Apache, can you please give me more details about the Apache configuration?

**Comment by Bonze255** [comment]
**ssl-params.conf**
> SSLCipherSuite EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH
> SSLProtocol All -SSLv2 -SSLv3 -TLSv1 -TLSv1.1
> SSLHonorCipherOrder On
> 
> # Disable preloading HSTS for now.  You can use the commented out header line that includes
> # the "preload" directive if you understand the implications.
> # Header always set Strict-Transport-Security "max-age=63072000; includeSubDomains; preload"
> Header always set X-Frame-Options DENY
> Header always set X-Content-Type-Options nosniff
> # Requires Apache >= 2.4
> SSLCompression off
> SSLUseStapling on
> SSLStaplingCache "shmcb:logs/stapling-cache(150000)"
> # Requires Apache >= 2.4.11
> SSLSessionTickets Off
> 

**default-ssl.conf**
.......
> 
>                 #   SSL Engine Switch:
>                 #   Enable/Disable SSL for this virtual host.
>                 SSLEngine on
> 
>                 #   A self-signed (snakeoil) certificate can be created by installing
>                 #   the ssl-cert package. See
>                 #   /usr/share/doc/apache2/README.Debian.gz for more info.
>                 #   If both key and certificate are stored in the same file, only the
>                 #   SSLCertificateFile directive is needed.
>                 SSLCertificateFile      /etc/apache2/ssl/apache.crt
>                 SSLCertificateKeyFile /etc/apache2/apache.key
......

**Comment by florian-h05** [comment]
The SSL configuration of Apache is not that important I think, can you please share the actual server configuration (e.g. location block or whatever it is in Apache) of the proxied webrtc-sip-gw?

**Comment by Bonze255** [comment]
sry i dont know what you mean?!

**Comment by florian-h05** [comment]
Both the default-ssl.conf and ssl-params.conf files are not the files where you configure which sites the Apache webserver should serve and what it should proxy. I need your proxy configuration to check whether it is fine.

**Comment by Bonze255** [comment]
![grafik](https://github.com/florian-h05/webrtc-sip-gw/assets/16838128/0a3e0be4-9253-40c7-9318-83dc856b1e52)
i think, tehere is no proxy configuration -> then i could use also an nginx? reverse proxy from your example ?

**Comment by florian-h05** [comment]
TBH, it seems to me that you neither have experience with Apache nor with NGINX. 

Before trying to get up this container behind a proxy, I would rather recommend to use it with its internal TLS (the README describes how to generate the certificates), or in case you want to use a reverse proxy, get some experience with Apache or NGINX first.

I personally prefer NGINX, as I have both tried and it felt like NGINX is easier to use. In case you want to set up a reverse proxy, LMGT4You: https://www.digitalocean.com/community/tutorials/how-to-configure-nginx-as-a-reverse-proxy-on-ubuntu-22-04.

Please understand that I cannot help with NGINX or Apache set up in general, rather ask for help in the according forums or probably Google a guide or watch a video tutorial.

**Comment by Bonze255** [comment]
debian has an specially configurable apache2 :D 
now iam using the ssl certificate for the wss and apache2.. now the connection works..  but im getting the same 488 error (Not Acceptable here)

the log from your docker container:

> 
> INFO: [563E32799F666EFB@192.168.178.1]: [core] --- Tag '2FC4E4A814F9F39A', created 0:03 ago for branch ''
> INFO: [563E32799F666EFB@192.168.178.1]: [core] ---     subscribed to ''
> INFO: [563E32799F666EFB@192.168.178.1]: [core] ---     subscribed to ''
> INFO: [563E32799F666EFB@192.168.178.1]: [core] ---     subscription for ''
> INFO: [563E32799F666EFB@192.168.178.1]: [core] ------ Media #1 (audio over RTP/AVP) using unknown codec
> INFO: [563E32799F666EFB@192.168.178.1]: [core] --------- Port  192.168.178.57:23488 <>   192.168.178.1:7080 , SSRC 0, 0 p, 0 b, 0 e, 3 ts
> INFO: [563E32799F666EFB@192.168.178.1]: [core] --------- Port  192.168.178.57:23489 <>   192.168.178.1:7081  (RTCP), SSRC 0, 0 p, 0 b, 0 e, 3 ts
> INFO: [563E32799F666EFB@192.168.178.1]: [core] --- Tag '', created 0:03 ago for branch 'z9hG4bKB5D322333A9B4C580'
> INFO: [563E32799F666EFB@192.168.178.1]: [core] ---     subscription for '2FC4E4A814F9F39A'
> INFO: [563E32799F666EFB@192.168.178.1]: [core] ------ Media #1 (audio over RTP/SAVPF) using unknown codec
> INFO: [563E32799F666EFB@192.168.178.1]: [core] --------- Port  192.168.178.57:23478 <>                :0    , SSRC 0, 0 p, 0 b, 0 e, 3 ts
> INFO: [563E32799F666EFB@192.168.178.1]: [core] --- Tag '', created 0:03 ago for branch 'z9hG4bKB5D322333A9B4C581'
> INFO: [563E32799F666EFB@192.168.178.1]: [core] ---     subscribed to '2FC4E4A814F9F39A'
> INFO: [563E32799F666EFB@192.168.178.1]: [core] ---     subscription for '2FC4E4A814F9F39A'
> INFO: [563E32799F666EFB@192.168.178.1]: [core] ------ Media #1 (audio over RTP/AVP) using unknown codec
> INFO: [563E32799F666EFB@192.168.178.1]: [core] --------- Port  192.168.178.57:23400 <>                :0    , SSRC 0, 0 p, 0 b, 0 e, 3 ts
> INFO: [563E32799F666EFB@192.168.178.1]: [core] --------- Port  192.168.178.57:23401 <>                :0     (RTCP), SSRC 0, 0 p, 0 b, 0 e, 3 ts
> INFO: [563E32799F666EFB@192.168.178.1]: [control] Replying to 'delete' from 127.0.0.1:41559 (elapsed time 0.000634 sec)
>  9(46) INFO: <script>: Failure: <null> 1(38) INFO: <script>: START: ACK from sip:**610@fritz.box (IP:192.168.178.1:5060)
>  1(38) INFO: <script>: Setting new Contact header: <null>
>  9(46) INFO: <script>: HTTP Request Received
>  9(46) WARNING: websocket [ws_handshake.c:271]: ws_handle_handshake(): required headers not present
> 
>  

the question is now, where are the codecs defined and why is my codec unknown? I use the newest  AVM FRITZ!Box 7430 146.07.31 (Sep  2 2023) ?

**Comment by florian-h05** [comment]
> now iam using the ssl certificate for the wss and apache2..

Good :+1: 

> the question is now, where are the codecs defined and why is my codec unknown?

I am using a Fritz!Box 7590 with the latest Fritz!OS 7.57 and it just works fine. 

I would start searching for the problem on your client side, not at the Fritz!Box. What is your client?

**Comment by Bonze255** [comment]
what is your setup? 

fritzbox->webrtc-sip-gw->webserver->nginx 


you use nginx only for redirecting and https? 

i try to use only apache2 for wss and https, but i think, there must been an additional setting for wss.. i think my setup should the same as yours..

**Comment by florian-h05** [comment]
My setup is:

DoorBird Door Station --SIP-- Fritz!Box --SIP-- webrtc-sip-gw --SIP-over-WebSocket-- Nginx reverse proxy --SIP-over-WebSocket Secure-- JsSIP

Nginx is only used as a reverse proxy to provide WebSocket Secure, which is needed for some OSes, e.g. iOS.

The whole Nginx configuration used is the simple location block from the README.

**Comment by Bonze255** [comment]
Thats funny, i would use it, also with an doorbird 😂, 

Today I have reset my test vm. I can save and control all things from the doorbird over python, but the sound  is missing.. smartvisu use also websockets over http/s , so i must test the whole system..

**Comment by Bonze255** [comment]
all scripts work correctly now, but the error from jssip is the same.. 

i have nginx as reverse proxy

> server {

 listen 443 ssl;
   # server_name         ;
    ssl_certificate    /home/smarthome/dockergateway/ssl/sipgw.crt;
    ssl_certificate_key /home/smarthome/dockergateway/ssl/sipgw.key;
    ssl_protocols       TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
        root /var/www/html;
        index index.html;
#zugriff Webrtc_SIP_GW
location /sip {
        proxy_pass                    http://127.0.0.1:8090; # Adjust to your webrtc-sip-gw Docker host's IP
        proxy_http_version            1.1;
        proxy_set_header Upgrade      $http_upgrade;
        proxy_set_header Connection   "upgrade";
        proxy_read_timeout            86400;
    }
#zugriff websocket
  location = / {
        auth_basic "Restricted Area: smartVISU";
        auth_basic_user_file /etc/nginx/.smartvisu;
        proxy_pass http://192.168.178.91:2424;
    }

    # Zugriff auf die smartVISU mit Basic Auth
    location /smartvisu {
        auth_basic "Restricted Area: smartVISU";
        auth_basic_user_file /etc/nginx/.smartvisu;
        proxy_pass http://192.168.178.91/smartvisu/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

apache webservers config  webserver :80
and Jssip is configuratet as wss 

> var socket = new JsSIP.WebSocketInterface('wss://192.168.178.57/sip');

the connection is succesfull, but i cant not answer a call.. 

which version if jssip do you use?

**Comment by florian-h05** [comment]
> Why is the nginx config not

In this use case, the whole point of having NGINX as reverse proxy here is to enable HTTPS/WSS for HTTP/WS without having to configure this in webrtc-sip-gw. The NGINX snippet from the README works, I won't answer any further questions regarding NGINX. I

> which version if jssip do you use?

openHAB Main UI is currently on 3.10.x.
You can find the source code here: https://github.com/openhab/openhab-webui/blob/881a8b787e1eb707fdba12315b83f06659f9a1c8/bundles/org.openhab.ui/web/src/components/widgets/system/oh-sipclient.vue.

This is likely to be my last comment at this issue, I neither have the time nor the resources to debug your installation or help you doing that. All I can say is that it works very fine for me together with the openHAB Main UI, where I implemented the SIP client. For other clients than openHAB's Main UI, I cannot offer support.

**Comment by florian-h05** [comment]
Nice to hear that it works now, and thanks for sharing the result of your investigation!
